# Generated by Django 5.2.7 on 2025-11-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'تم إنشاء الطلب'), ('order_status_changed', 'تغير حالة الطلب'), ('order_shipped', 'تم شحن الطلب'), ('order_delivered', 'تم تسليم الطلب'), ('commission_calculated', 'تم حساب العمولة')], max_length=30, verbose_name='نوع الإشعار'),
        ),
    ]
