# Generated by Django 5.2.7 on 2025-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('manager', 'مدير'), ('seller', 'بائع'), ('buyer', 'مشتري')], max_length=10, verbose_name='دور المستخدم')),
                ('product_category', models.CharField(blank=True, choices=[('phones', 'هواتف'), ('computers', 'أجهزة كمبيوتر'), ('accessories', 'إكسسوارات')], max_length=20, null=True, verbose_name='فئة المنتج')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات العمولة',
                'verbose_name_plural': 'إعدادات العمولات',
                'unique_together': {('user_role', 'product_category')},
            },
        ),
    ]
