# Generated by Django 5.2.7 on 2025-11-06 18:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_commissionsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='سبب النزاع')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', max_length=15, verbose_name='الحالة')),
                ('resolution', models.CharField(choices=[('pending', 'قيد الانتظار'), ('buyer_favor', 'صالح المشتري'), ('seller_favor', 'صالح البائع'), ('refund', 'استرداد'), ('partial_refund', 'استرداد جزئي')], default='pending', max_length=15, verbose_name='الحل المقترح')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='الطلب')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'نزاع',
                'verbose_name_plural': 'النزاعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة الأساسية')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة لكل كيلوغرام')),
                ('delivery_time', models.CharField(max_length=50, verbose_name='وقت التسليم المتوقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'شركة شحن',
                'verbose_name_plural': 'شركات الشحن',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الضريبة')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الضريبة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'معدل ضريبي',
                'verbose_name_plural': 'معدلات ضريبية',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='الرخصة التجارية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم النشاط التجاري'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='ids/', verbose_name='صورة الهوية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة التحقق'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شركة الشحن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الشحن'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التتبع'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='حد التنبيه عند انخفاض المخزون'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية المخزون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى'), ('dispute', 'نزاع')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'تم إنشاء الطلب'), ('order_status_changed', 'تغير حالة الطلب'), ('order_shipped', 'تم شحن الطلب'), ('order_delivered', 'تم تسليم الطلب'), ('commission_calculated', 'تم حساب العمولة'), ('low_stock', 'انخفاض المخزون'), ('dispute_opened', 'فتح نزاع'), ('dispute_resolved', 'حل النزاع'), ('verification_status_changed', 'تغير حالة التحقق')], max_length=30, verbose_name='نوع الإشعار'),
        ),
    ]