# Generated by Django 5.2.7 on 2025-11-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_advanced_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('QAR', 'Qatari Riyal'), ('OMR', 'Omani Rial'), ('BHD', 'Bahraini Dinar'), ('JOD', 'Jordanian Dinar')], default='USD', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('QAR', 'Qatari Riyal'), ('OMR', 'Omani Rial'), ('BHD', 'Bahraini Dinar'), ('JOD', 'Jordanian Dinar')], default='USD', max_length=3, verbose_name='العملة'),
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('products', models.ManyToManyField(to='store.product', verbose_name='المنتجات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مقارنة منتجات',
                'verbose_name_plural': 'ممارسات مقارنة المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - سيء'), (2, '2 - مقبول'), (3, '3 - جيد'), (4, '4 - جيد جداً'), (5, '5 - ممتاز')], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='شراء مؤكد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'مراجعات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قائمة الرغبات',
                'verbose_name_plural': 'قوائم الرغبات',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
