# Generated by Django 5.2.7 on 2025-11-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_currency_alter_payment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحملة')),
                ('platform', models.CharField(choices=[('facebook', 'فيسبوك'), ('google', 'جوجل'), ('instagram', 'إنستغرام'), ('twitter', 'تويتر')], max_length=20, verbose_name='المنصة')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الميزانية')),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المنفق')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='النقرات')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='الظهور')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='التحويلات')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حملة إعلانية',
                'verbose_name_plural': 'حملات إعلانية',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الكوبون')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], max_length=10, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_to', models.DateTimeField(verbose_name='صالح حتى')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='مرات الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'كوبونات',
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('recipients', models.TextField(help_text='قائمة البريد الإلكتروني مفصولة بفواصل', verbose_name='المستلمون')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدول'), ('sent', 'مرسل'), ('cancelled', 'ملغى')], default='draft', max_length=10, verbose_name='الحالة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='مجدول في')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='أرسل في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حملة بريد إلكتروني',
                'verbose_name_plural': 'حملات البريد الإلكتروني',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المكافأة')),
                ('reward_type', models.CharField(choices=[('discount', 'خصم'), ('free_product', 'منتج مجاني'), ('shipping', 'شحن مجاني')], max_length=20, verbose_name='نوع المكافأة')),
                ('points_required', models.PositiveIntegerField(verbose_name='النقاط المطلوبة')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم')),
                ('active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مكافأة الولاء',
                'verbose_name_plural': 'مكافآت الولاء',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='النقاط')),
                ('level', models.CharField(default='bronze', max_length=20, verbose_name='المستوى')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي الإنفاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'برنامج الولاء',
                'verbose_name_plural': 'برامج الولاء',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='مفتاح الجلسة')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('click', 'نقر'), ('add_to_cart', 'إضافة للسلة'), ('purchase', 'شراء'), ('search', 'بحث')], max_length=20, verbose_name='الإجراء')),
                ('metadata', models.TextField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سلوك المستخدم',
                'verbose_name_plural': 'سلوكيات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توصية المستخدم',
                'verbose_name_plural': 'توصيات المستخدمين',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
