# Generated by Django 5.2.7 on 2025-11-08 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_advertisementcampaign_coupon_emailcampaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_system', models.CharField(max_length=50, verbose_name='نظام المحاسبة')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف المعاملة')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='تمت المزامنة في')),
                ('sync_status', models.CharField(default='pending', max_length=20, verbose_name='حالة المزامنة')),
                ('accounting_data', models.TextField(blank=True, null=True, verbose_name='بيانات المحاسبة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تكامل المحاسبة',
                'verbose_name_plural': 'تكاملات المحاسبة',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='مفتاح الجلسة')),
                ('event_type', models.CharField(choices=[('page_view', 'عرض الصفحة'), ('product_view', 'عرض المنتج'), ('add_to_cart', 'إضافة للسلة'), ('checkout', 'الدفع'), ('purchase', 'شراء'), ('search', 'بحث')], max_length=20, verbose_name='نوع الحدث')),
                ('url', models.URLField(blank=True, null=True, verbose_name='الرابط')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='المرجع')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='وكيل المستخدم')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الطابع الزمني')),
                ('metadata', models.TextField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحليلات',
                'verbose_name_plural': 'التحليلات',
            },
        ),
        migrations.CreateModel(
            name='ExternalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='المعرف الخارجي')),
                ('system_name', models.CharField(max_length=50, verbose_name='اسم النظام')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('external_stock', models.PositiveIntegerField(default=0, verbose_name='المخزون الخارجي')),
                ('sync_status', models.CharField(default='pending', max_length=20, verbose_name='حالة المزامنة')),
                ('api_endpoint', models.URLField(blank=True, null=True, verbose_name='نقطة نهاية API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مخزون خارجي',
                'verbose_name_plural': 'المخزونات الخارجية',
            },
        ),
        migrations.CreateModel(
            name='ShippingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fedex', 'FedEx'), ('dhl', 'DHL'), ('ups', 'UPS'), ('aramex', 'Aramex'), ('smsa', 'SMSA')], max_length=20, verbose_name='مزود الشحن')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التتبع')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='التسليم المتوقع')),
                ('status', models.CharField(default='pending', max_length=30, verbose_name='الحالة')),
                ('api_response', models.TextField(blank=True, null=True, verbose_name='استجابة API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تكامل الشحن',
                'verbose_name_plural': 'تكاملات الشحن',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'فيسبوك'), ('twitter', 'تويتر'), ('instagram', 'إنستغرام'), ('linkedin', 'لينكدإن'), ('pinterest', 'بينتيريست')], max_length=20, verbose_name='المنصة')),
                ('post_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف المنشور')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='مجدول في')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='نُشر في')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تكامل وسائل التواصل',
                'verbose_name_plural': 'تكاملات وسائل التواصل',
            },
        ),
    ]
