# Generated by Django 5.2.7 on 2025-11-08 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_accountingintegration_analyticsintegration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('secret_key', models.CharField(max_length=100, verbose_name='المفتاح السري')),
                ('device_type', models.CharField(choices=[('totp', 'TOTP (Time-based)'), ('hotp', 'HOTP (Counter-based)')], max_length=20, verbose_name='نوع الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز MFA',
                'verbose_name_plural': 'أجهزة MFA',
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'تسجيل دخول ناجح'), ('login_failed', 'تسجيل دخول فاشل'), ('logout', 'تسجيل خروج'), ('password_change', 'تغيير كلمة المرور'), ('mfa_success', 'MFA ناجح'), ('mfa_failed', 'MFA فاشل'), ('suspicious_activity', 'نشاط مشبوه'), ('account_lockout', 'قفل الحساب'), ('permission_change', 'تغيير الصلاحيات')], max_length=30, verbose_name='نوع الحدث')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='وكيل المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الطابع الزمني')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='مشبوه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل أمان',
                'verbose_name_plural': 'سجلات الأمان',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('bank_account', 'حساب بنكي'), ('personal_id', 'هوية شخصية'), ('passport', 'جواز سفر'), ('address', 'عنوان'), ('phone', 'رقم هاتف')], max_length=20, verbose_name='نوع البيانات')),
                ('encrypted_data', models.TextField(verbose_name='البيانات المشفرة')),
                ('encryption_method', models.CharField(default='AES-256', max_length=50, verbose_name='طريقة التشفير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بيانات حساسة',
                'verbose_name_plural': 'بيانات حساسة',
            },
        ),
    ]
