# Generated by Django 4.2.26 on 2025-11-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_notification_user_alter_order_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['user', '-created_at'], name='store_commi_user_id_0d55c5_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['order', '-created_at'], name='store_commi_order_i_c7f1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['is_paid', '-created_at'], name='store_commi_is_paid_6d79f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='store_notif_user_id_c0d189_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-created_at'], name='store_notif_is_read_5c3997_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='store_notif_notific_91bd40_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='store_order_user_id_f28375_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='store_order_status_7b2658_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='store_order_user_id_c9744e_idx'),
        ),
    ]
