# Generated by Django 4.2.26 on 2025-11-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_commission_store_commi_user_id_0d55c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalinventory',
            unique_together={('product', 'external_id', 'system_name')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaintegration',
            unique_together={('product', 'platform')},
        ),
    ]
